# -*- coding: utf-8 -*-
"""MJ Conley Final Project DSC502

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dgwRwCSkzN3xBGFg0gvxRGagV_lF3C3G
"""

from google.colab import files
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from numpy import cov
from scipy.stats import pearsonr
from scipy.stats import spearmanr
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression

"""Welcome to MJ's DSC502 Final Project!
I will be walking you through my process, step- by- step.

--Pick a research question.

I don't know how most data folks go about picking projects, but I decided I wanted to conduct this as if it was a research project. I started with a research question. This took me very little time, I'm very curious and I was able to brainstorm something somewhat related and relevant to my Psych MA Thesis here as SCSU: public health.

My inital quesiotn was, 'Is there a relationship between abstinence- only State Public Education Mandates on Health Classes and risky behavior in youth?'

After deciding on this question, I began thinking about what concrete data I would need to answer this question.

--Find the necesary data to process.

And I did! But the file formats provided by the CDC for Youth Behavior Risk SUrvey were untenable in Colab, and after looking through the survey questions, I really didn't think enough of the data was useful for me. Link to original plans:https://www.cdc.gov/healthyyouth/data/yrbs/data.htm

I then went after data that would be easier for the scope of this project. After finding more Colab- accessible CDC tables, ( https://gis.cdc.gov/grasp/nchhstpatlas/tables.html ), I altered my research question:
'Is there a relationship between abstinence- only State Public Education Mandates on Health Classes and rates of STDS over the past 5 years?'

I added a comlumn to the dataframe based on this research:

https://worldpopulationreview.com/state-rankings/abstinence-only-education-states

It's a list of states where '1' indicates the presence of abstinence- only education in the 'abst' column. Binary data!

So, I got that data all set up a CSV and linked it to Colab.
"""

uploaded = files.upload()

df= pd.read_csv("final project data 2015-2019 - AtlasPlusTableData.csv")

df

"""To measure the relationship between abstinence- only education and STD rates per 100,000, I'm going start by seeing if there is correlation between abstinence- only education and STD rates per 100,000"""

covariance = cov(df['Rate per 100000'],df['Abst'])
print(covariance)

corr, _ = pearsonr(df['Rate per 100000'],df['Abst'])
print('Pearsons correlation: %.3f' % corr)

"""Then I ran a ran a scatter plot, disapointed in the SUPER weak relatioship-- I suspect this was because of the categorical data/ non- linear relationship.

Binary data has some advantages, but this is a disadavatage that I overlooked.

I would go on to run a scatter plot to confirm this. It was not, as I guessed that. SO, I tried Spearman's correlation coeff, just to see.

It was super useful to realize this data could not be linear, you will see why in a moment.
"""

y=df['Rate per 100000']
x=df['Abst']
plt.scatter(x,y)

corr, _ = spearmanr(df['Rate per 100000'],df['Abst'])
print('Spearmans correlation: %.3f' % corr)

"""Irrelevantly less weak, still too weak to indicate any kind of relationship.
I decided to try something else more interesting to see what I could find:

I sorted the data frame to focus  on each type of STD case per 100,000. I'm also going to a some other details to the or dataset, specifically population density by year, by state.

Basically, does abstinence-only sex ed and population density explain more of  the varaince in the cases each STD per 100,000 than just abstinence only education?
"""

uploaded = files.upload()

df1= pd.read_csv("2015-2019 final project data - SHEET OF DOOM.csv", usecols=[0,1,2,3,4,5,6,7,8,9])

df1

"""Note about the data from the years 2015-2019: they are calculated with ESTIMATED population counts from the governmnet, because these years did not have actual census counts taken.

2015-2019: https://www.census.gov/data/tables/time-series/demo/popest/2010s-state-total.html#par_textimage_1574439295

I had to do a bunch of data populating for square mile area and population by year in Google Sheets, because it was took less time to line up each state and year with the relevant data than in Colab. I actually had never used the VLOOKUP function before, so I learned that to accomplish this quickly.

 Because 2015-2019 had and populations change each year (and I couldn't get find an estimated population density for these years), it was a little complicated. Six look-up tables and an simple math function later, I had 1076 data points with associated population densities!

Square mileage area of each state was harvested from wikipedia.
"""

grouped = df1.groupby(['Indicator'])
df1c = grouped.get_group(('Chlamydia'))

"""I decided to try analyzing the STD data for Chlamydia first, but the process should be the same for each of the 4 other STD categories."""

df1c

df1c['Cases'].replace(',','', regex=True, inplace=True)

"""Ran into some trouble with the commas and data type, this corrects for that to make it processable in regression.

Because it was a weird, non- linear relationship, I used K- Nearest Neighbors Regression instead of linear regression to get a best- fit value (R^2)

**I need a refresher in statisical analysis, I can't remember some of the terminologies. Some of the verbage in this presentation is odd and may be incorrect.
"""

X = df1c.loc[:, ['PopDenEST', 'Abst']]
y = df1c.loc[:,'Rate per 100000']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1)

knn = KNeighborsRegressor(n_neighbors = 3, weights = 'uniform')

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print('R squared: ', knn.score(X_test, y_test))

"""With this model, ~%85 of the variance in cases of Chlamydia can be explained by population density and whether or not the state has abstinence only education.

This is pretty cool, that's a pretty strong relationship!
"""

df1c.to_csv('df1c.csv')
files.download('df1c.csv')

"""The rest of this code is being used to generate content for my streamlit app.

Unfortunately, there was some technical difficulties, possibly due to updates.Even the Github practice repository from last month no longer ran in Streamlit

So, the plots are not interactable, but they are here to look at.
"""

df00=(df1c.loc[df1c['Abst'] == 0])
df11=(df1c.loc[df1c['Abst'] == 1])

"""The app was intenede to show one of two bar graphs, depending on user selection of seuxal education type, so I seperated the data into two dataframes."""

df11

df00

"""Genrate the plots! Nothing fancy, gets the job done."""

cases= df11['Rate per 100000']
state= df11['Geography']
fig = plt.figure(figsize =(10, 7))
plt.barh(state, cases)
plt.title("Cases of Chlamydia by State, Abstinence- Only")
plt.xlabel('Rate of Cases Per 100,000')
plt.show()

cases= df00['Rate per 100000']
state= df00['Geography']
fig = plt.figure(figsize =(10, 7))
plt.barh(state, cases)
plt.title("Cases of Chlamydia by State, Non- Abstinence- Only")
plt.xlabel('Rate of Cases Per 100,000')
plt.show()

""""What is up with DC?"

I don't know! This information came from the CDC. I can imagine there is a scientific, publci- heatlh reason for this, I just don't know it.

At this point, I had the answer I was looking for, and started working on the visualizations and mounting it all into streamlit application.

Which is when I found it was wonky!

I will show you the code now, but I have no idea if it does what it is supposed to do (A selection of graphs based on user input.)

Future projects could include using COVID mandates or political affiliations by state on top of this data to look at how 2020's STD rates might be affected by adherence to CDC COVID restrictions or political affiliation.

I also wonder if states with more COVID deaths also had higher STD rates, or how states with 'better' low- income healthcae (or more statewide healthcare budget, or more healthcare workers per person in the populalation).

I'm making these notes for myself, for projects to try out in the future.

Thank you SO MUCH!
"""